# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv.xci
# IP: The module: 'clkdiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkdiv'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv.xci
# IP: The module: 'clkdiv' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/MiniMIPS32/MiniMIPS32.srcs/sources_1/ip/clkdiv/clkdiv_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkdiv'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
